version: '2.2'
services: 
  oficina:
    image: oficina-docker:aula2-volume
    build: .
    ports: 
     - 5010:5000
    volumes:
     - .:/usr/src
     - aula2-logs:/tmp
   
volumes:
  aula2-logs:
    external: true
